### See https://github.com/lindell/multi-gitter#config-file for all options

# The maximum number of concurrent runs.
concurrent: 1

branch: htmlunit-2.x-to-3.x

# What should happen if the branch already exist.
# Available values:
#   skip: Skip making any changes to the existing branch and do not create a new pull request.
#   replace: Replace the existing content of the branch by force pushing any new changes, then reuse any existing pull request, or create a new one if none exist.
conflict-strategy: skip

# Comment this out if you don't have permissions on the repository
labels:
 - dependencies

# The level of logging that should be made. Available values: trace, debug, info, error.
log-level: info

# Fork the repository instead of creating a new branch on the same owner.
### Needed to operate on repositories where you don't have enought permissions
fork: true

# If set, make the fork to the defined value. Default behavior is for the fork to be on the logged in user.
### Set to a test organisation to not polute your GitHub profile with many forks
# fork-owner: timja-bot

commit-message: Upgrade HtmlUnit from 2.x to 3.x
pr-body: |
  _This is an autogenerated PR for updating HtmlUnit_

  It follows the [migration guide](https://www.htmlunit.org/migration.html)

  <details>
    <summary>Migration steps for cases the script can't handle</summary>

    This migration currently can't handle `HtmlOption` changes properly.
    If it fails to compile on `HtmlOption` then revert the specific case:
    ```diff
  --- a/src/test/java/hudson/plugins/emailext/ExtendedEmailPublisherDescriptorTest.java
  +++ b/src/test/java/hudson/plugins/emailext/ExtendedEmailPublisherDescriptorTest.java
  @@ -114,7 +114,7 @@ public class ExtendedEmailPublisherDescriptorTest {
          assertEquals(
                  "Plain text should be selected by default",
                  "text/plain",
  -                contentType.getSelectedOptions().get(0).getValue());
  +                contentType.getSelectedOptions().get(0).getValueAttribute());
    ```

    </details>

  Ping `@timja` if any questions

  _[script source](https://github.com/timja/htmlunit-2.x-to-3.x)_
# # # The name, including owner of a GitHub repository in the format "ownerName/repoName".
# repo:
#   - jenkinsci/artifact-manager-s3-plugin
# #   - mylittlecorp/jenkins-infra-test-plugin
# #   - lemeurherve/jenkins-infra-test-plugin
#   - jenkinsci/jenkins-infra-test-plugin
# # #   - jenkinsci/test-results-aggregator-plugin

# # The name of a GitHub organization. All repositories in that organization will be used.
org:
  - jenkinsci


# Skip changes on specified repositories, the name is including the owner of repository in the format "ownerName/repoName".
skip-repo: ["jenkinsci/jenkins", "jenkinsci/junit-plugin", "jenkinsci/git-plugin", "jenkinsci/gerrit-trigger-plugin"]
